const { test } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const { addDjiToMainApplication, addDjiToManifest, readApiKey } = require("./dji-mods");

// MainApplication.kt as generated by Expo SDK 57 (expo-template-bare-minimum 57.0.29).
const MAIN_APP = fs.readFileSync(path.join(__dirname, "dji-mods.fixture.MainApplication.kt"), "utf8");

test("MainApplication: DJI install in attachBaseContext and init right after super.onCreate()", () => {
  const out = addDjiToMainApplication(MAIN_APP);
  assert.match(out, /override fun attachBaseContext\(base: android\.content\.Context\) \{\n\s+super\.attachBaseContext\(base\)\n\s+expo\.modules\.djidrone\.DjiSdk\.install\(this\)/);
  assert.match(out, /super\.onCreate\(\)\n\s+expo\.modules\.djidrone\.DjiSdk\.init\(this\)/);
  assert.equal(addDjiToMainApplication(out), out, "running twice changes nothing");
});

test("MainApplication: fails loudly if the template changes", () => {
  assert.throws(() => addDjiToMainApplication("class Other {}"));
});

function manifest() {
  return {
    manifest: {
      application: [
        {
          $: { "android:name": ".MainApplication" },
          activity: [{ $: { "android:name": ".MainActivity" }, "intent-filter": [{ action: [{ $: { "android:name": "android.intent.action.MAIN" } }] }] }],
        },
      ],
    },
  };
}

test("Manifest: App Key and USB controller filter, added once", () => {
  const m = addDjiToManifest(addDjiToManifest(manifest(), "KEY1"), "KEY2");
  const app = m.manifest.application[0];
  const keys = app["meta-data"].filter((x) => x.$["android:name"] === "com.dji.sdk.API_KEY");
  assert.equal(keys.length, 1);
  assert.equal(keys[0].$["android:value"], "KEY2");
  const act = app.activity[0];
  const usb = act["intent-filter"].filter((f) => f.action.some((a) => a.$["android:name"].endsWith("USB_ACCESSORY_ATTACHED")));
  assert.equal(usb.length, 1);
  assert.equal(act["meta-data"].length, 1);
  assert.equal(act["meta-data"][0].$["android:resource"], "@xml/accessory_filter");
});

test("App Key is required", () => {
  assert.throws(() => readApiKey({}), /DJI_API_KEY is not set/);
  assert.equal(readApiKey({ DJI_API_KEY: " abc " }), "abc");
});
