plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.djidrone'
version = '0.1.0'

// DJI Mobile SDK v5. Keep the three versions the same.
def djiSdkVersion = '5.18.0'

android {
  namespace 'expo.modules.djidrone'
  defaultConfig {
    minSdkVersion 24
  }
}

dependencies {
  implementation "com.dji:dji-sdk-v5-aircraft:${djiSdkVersion}"
  compileOnly "com.dji:dji-sdk-v5-aircraft-provided:${djiSdkVersion}"
  runtimeOnly "com.dji:dji-sdk-v5-networkImp:${djiSdkVersion}"
}
